### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by zinedK** [Mino5531/scrum-project#1]
F1:
Ich als Verwalter möchte meine Daten speichern, einsehen und abrufen können

F2:
Ich als Benutzer möchte mich registrieren und einloggen können, als auch meine Daten einsehen
Ich als Verwalter möchte die User Daten einsehen und erfassen können

F3:
Ich als Benutzer möchte eien Auswahl an Spielen haben 
Ich als Verwalter möchte die Spiele administrieren können

F4:
Ich als Benutzer möchte:
	Roulette
	Blackjack
	Slots
	(Lotto)
spielen können

F5:
Ich als Verwalter möchte die Daten der User bearbeiten können

F6:
Ich als Verwalter möchte die Möglichkeit haben, die Konten/Daten der User zu löschen/sperren

F7:
Ich als Verwalter möchte eine spezielle Oberfläche für meinen Status haben

FR1:
Ich als Verwalter möchte neue Spiele einfach hinzufügen können
Ich als bBnutzer möchte neue Spiele testen/spielen können

FR2:
Ich als Benutzer möchte mögliche Spiele mit anderen Spielern online zusammen spielen

**Comment by Mino5531** [comment]
Hi,
Sieht gut aus allerdings sollten die einzelnen Stories als jeweils eigenes Issue gemacht werden oder?
